name: Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  deploy:
    name: deploy-gcf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
      - name: Deploy to GCF
        run: |
          gcloud functions deploy $FUNCTION_NAME
          --gen2
          --service-account $IDENTITY_EMAIL
          --region=$FUNCTION_REGION
          --runtime=$FUNCTION_RUNTIME
          --memory=$FUNCTION_MEMORY
          --timeout=$FUNCTION_TIMEOUT
          --min-instances=0
          --max-instances=10
          --entry-point=main
          --trigger-http
          --allow-unauthenticated
          --set-env-vars=PROJECT_ID=$PROJECT_ID