stages:
  - temp_logs_function_v3_deploy

temp_logs_function_v3_deploy:
  stage: temp_logs_function_v3_deploy
  image: google/cloud-sdk:latest
  variables:
    FUNCTION_NAME: temp_logs_function_v3
    DIRECTORY_NAME: temp_logs_function
    FUNCTION_REGION: europe-central2
    FUNCTION_RUNTIME: python311
    FUNCTION_MEMORY: 256MB
    FUNCTION_TIMEOUT: 60s
    FUNCTION_ENTRY_POINT: main
    FUNCTION_MIN_INSTANCES: 0
    FUNCTION_MAX_INSTANCES: 1
    FUNCTION_TRIGGER_TYPE: --trigger-http
    #can be found here https://cloud.google.com/sdk/gcloud/reference/functions/deploy
    FUNCTION_ADDITIONAL_PARAMS: --allow-unauthenticated
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
      changes: # Include the job and set to when:manual if any of the follow paths match a modified file.
        - $DIRECTORY_NAME/*
  script:
    - PATH="google-cloud-sdk/bin:${PATH}"
    - cd $DIRECTORY_NAME
    # Authenticate using the service account stored here: https://gitlab.com/groups/{YOUR_GITLAB_PROJECT}/-/settings/ci_cd
    - gcloud auth activate-service-account --key-file ${{ secrets.GCP_KEY_FILE }}
    - gcloud config set project $PROJECT_ID
    - gcloud functions deploy $FUNCTION_NAME
                              --region=$FUNCTION_REGION
                              --runtime=$FUNCTION_RUNTIME
                              --memory=$FUNCTION_MEMORY
                              --timeout=$FUNCTION_TIMEOUT
                              --entry-point=$FUNCTION_ENTRY_POINT
                              --min-instances=$FUNCTION_MIN_INSTANCES
                              --max-instances=$FUNCTION_MAX_INSTANCES      
                              $FUNCTION_TRIGGER_TYPE
                              $FUNCTION_ADDITIONAL_PARAMS
  when: manual