name: Deploy Google Function
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: 'deploy-gcf'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'


      - name: 'Google auth'
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          service_account: '${{ secrets.GCP_KEY_FILE }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: 'Deploy to GCF'

        variables:
          FUNCTION_NAME: temp_logs_function_v3
          DIRECTORY_NAME: temp_logs_function
          FUNCTION_REGION: europe-central2
          FUNCTION_RUNTIME: python311
          FUNCTION_MEMORY: 256MB
          FUNCTION_TIMEOUT: 60s
          FUNCTION_ENTRY_POINT: main
          FUNCTION_MIN_INSTANCES: 0
          FUNCTION_MAX_INSTANCES: 1
          FUNCTION_TRIGGER_TYPE: --trigger-http
          #can be found here https://cloud.google.com/sdk/gcloud/reference/functions/deploy
          FUNCTION_ADDITIONAL_PARAMS: --allow-unauthenticated

        run: |
          gcloud functions deploy $FUNCTION_NAME
          --gen2
          --service-account ${{ secrets.SERVICE_ACCOUNT_KEY }}
          --region=$FUNCTION_REGION
          --runtime=$FUNCTION_RUNTIME
          --memory=$FUNCTION_MEMORY
          --timeout=$FUNCTION_TIMEOUT
          --min-instances=0
          --max-instances=10
          --entry-point=record
          --trigger-http
          --allow-unauthenticated